sudo: required

language: python

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t $DOCKER_USERNAME/plantuml:latest .
  - docker push $DOCKER_USERNAME/plantuml:latest
