sudo: required

language: python

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build --target latest -t $DOCKER_USERNAME/plantuml:latest .
  - docker push $DOCKER_USERNAME/plantuml:latest
  - docker build --target specific --build-arg version=1.2019.7 -t $DOCKER_USERNAME/plantuml:1.2019.7 .
  - docker push $DOCKER_USERNAME/plantuml:1.2019.7
  - docker build --target specific --build-arg version=1.2019.6 -t $DOCKER_USERNAME/plantuml:1.2019.6 .
  - docker push $DOCKER_USERNAME/plantuml:1.2019.6
  - docker build --target specific --build-arg version=1.2019.5 -t $DOCKER_USERNAME/plantuml:1.2019.5 .
  - docker push $DOCKER_USERNAME/plantuml:1.2019.5
  - docker build --target specific --build-arg version=1.2019.4 -t $DOCKER_USERNAME/plantuml:1.2019.4 .
  - docker push $DOCKER_USERNAME/plantuml:1.2019.4
  - docker build --target specific --build-arg version=1.2019.3 -t $DOCKER_USERNAME/plantuml:1.2019.3 .
  - docker push $DOCKER_USERNAME/plantuml:1.2019.3
  - docker build --target specific --build-arg version=1.2019.2 -t $DOCKER_USERNAME/plantuml:1.2019.2 .
  - docker push $DOCKER_USERNAME/plantuml:1.2019.2
  - docker build --target specific --build-arg version=1.2019.1 -t $DOCKER_USERNAME/plantuml:1.2019.1 .
  - docker push $DOCKER_USERNAME/plantuml:1.2019.1
  - docker build --target specific --build-arg version=1.2019.0 -t $DOCKER_USERNAME/plantuml:1.2019.0 .
  - docker push $DOCKER_USERNAME/plantuml:1.2019.0
  - docker build --target specific --build-arg version=1.2018.14 -t $DOCKER_USERNAME/plantuml:1.2018.14 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.14
  - docker build --target specific --build-arg version=1.2018.13 -t $DOCKER_USERNAME/plantuml:1.2018.13 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.13
  - docker build --target specific --build-arg version=1.2018.12 -t $DOCKER_USERNAME/plantuml:1.2018.12 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.12
  - docker build --target specific --build-arg version=1.2018.11 -t $DOCKER_USERNAME/plantuml:1.2018.11 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.11
  - docker build --target specific --build-arg version=1.2018.10 -t $DOCKER_USERNAME/plantuml:1.2018.10 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.10
  - docker build --target specific --build-arg version=1.2018.9 -t $DOCKER_USERNAME/plantuml:1.2018.9 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.9
  - docker build --target specific --build-arg version=1.2018.8 -t $DOCKER_USERNAME/plantuml:1.2018.8 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.8
  - docker build --target specific --build-arg version=1.2018.7 -t $DOCKER_USERNAME/plantuml:1.2018.7 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.7
  - docker build --target specific --build-arg version=1.2018.6 -t $DOCKER_USERNAME/plantuml:1.2018.6 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.6
  - docker build --target specific --build-arg version=1.2018.5 -t $DOCKER_USERNAME/plantuml:1.2018.5 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.5
  - docker build --target specific --build-arg version=1.2018.4 -t $DOCKER_USERNAME/plantuml:1.2018.4 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.4
  - docker build --target specific --build-arg version=1.2018.3 -t $DOCKER_USERNAME/plantuml:1.2018.3 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.3
  - docker build --target specific --build-arg version=1.2018.2 -t $DOCKER_USERNAME/plantuml:1.2018.2 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.2
  - docker build --target specific --build-arg version=1.2018.1 -t $DOCKER_USERNAME/plantuml:1.2018.1 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.1
  - docker build --target specific --build-arg version=1.2018.0 -t $DOCKER_USERNAME/plantuml:1.2018.0 .
  - docker push $DOCKER_USERNAME/plantuml:1.2018.0
  - docker build --target specific --build-arg version=1.2017.20 -t $DOCKER_USERNAME/plantuml:1.2017.20 .
  - docker push $DOCKER_USERNAME/plantuml:1.2017.20
  - docker build --target specific --build-arg version=1.2017.19 -t $DOCKER_USERNAME/plantuml:1.2017.19 .
  - docker push $DOCKER_USERNAME/plantuml:1.2017.19
  - docker build --target specific --build-arg version=1.2017.18 -t $DOCKER_USERNAME/plantuml:1.2017.18 .
  - docker push $DOCKER_USERNAME/plantuml:1.2017.18
  - docker build --target specific --build-arg version=1.2017.16 -t $DOCKER_USERNAME/plantuml:1.2017.16 .
  - docker push $DOCKER_USERNAME/plantuml:1.2017.16
  - docker build --target specific --build-arg version=1.2017.15 -t $DOCKER_USERNAME/plantuml:1.2017.15 .
  - docker push $DOCKER_USERNAME/plantuml:1.2017.15
  - docker build --target specific --build-arg version=1.2017.14 -t $DOCKER_USERNAME/plantuml:1.2017.14 .
  - docker push $DOCKER_USERNAME/plantuml:1.2017.14
  - docker build --target specific --build-arg version=1.2017.13 -t $DOCKER_USERNAME/plantuml:1.2017.13 .
  - docker push $DOCKER_USERNAME/plantuml:1.2017.13
  - docker build --target specific --build-arg version=1.2017.12 -t $DOCKER_USERNAME/plantuml:1.2017.12 .
  - docker push $DOCKER_USERNAME/plantuml:1.2017.12
  - docker build --target specific --build-arg version=2017.11 -t $DOCKER_USERNAME/plantuml:2017.11 .
  - docker push $DOCKER_USERNAME/plantuml:2017.11
  - docker build --target specific --build-arg version=2017.10 -t $DOCKER_USERNAME/plantuml:2017.10 .
  - docker push $DOCKER_USERNAME/plantuml:2017.10
  - docker build --target specific --build-arg version=2017.09 -t $DOCKER_USERNAME/plantuml:2017.09 .
  - docker push $DOCKER_USERNAME/plantuml:2017.09
  - docker build --target specific --build-arg version=2017.08 -t $DOCKER_USERNAME/plantuml:2017.08 .
  - docker push $DOCKER_USERNAME/plantuml:2017.08
